import { Box, Button, Container, Typography } from "@mui/material";
import Grid from "@mui/material/Grid";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>GutendexApp - Library</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container maxWidth="sm">
        <Box
          sx={{
            my: 4,
            display: "flex",
            flexDirection: "column",
            justifyContent: "center",
            alignItems: "center",
          }}
        >
          <Typography variant="h4" component="h1" gutterBottom>
            MaterialUI test
          </Typography>
        </Box>
      </Container>
    </>
  );
}
